### PR TITLE
feat(nook1208): Feb 2nd plan completed

### PR DESCRIPTION
**Pull request by nook1208**
Signed-off-by: Sunwook Eom <sunwook5492@gmail.com>

## 완료된 목표 3가지를 적어주세요

1. [Rust-os: Write Raspberry Pi device driver](https://github.com/nook1208/rust-rasp-os/commits/master)
2. [English: Anki: Add some cards to my decks](https://github.com/nook1208/english/commits/main)
3. [English: Listen any video or audio file & Write all sentences](https://github.com/nook1208/english/commits/main)

## 다음주 목표 3가지를 적어주세요

1. Rust-os: Use device driver in kernel start function
2. English: Anki: Add some cards to my decks
3. English: Listen any video or audio file & Write all sentences

### CODE REVIEW

**Review by huisam — APPROVED** [review]
한 주도 고생많으셨습니다 ㅎㅎ 👍

**Review by minhyungPark — CHANGES_REQUESTED** [review]
현재 README 위치가 `2021/02/14/` 밑에 있는데, 본인 폴더 하위로 변경 부탁드립니다

**Review by minhyungPark — APPROVED** [review]
수고하셨습니다 👍

**Review by kerochuu — APPROVED** [review]
수고하셨습니다😊

**Pull request merged**
