### PR TITLE
feat(jjeda): Complete 210207

### PR DESCRIPTION
**Pull request by jjeda**
## 완료된 목표 3가지를 적어주세요

1. [Os Oh yes 1장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#operation-system)
2. [Os Oh yes 2장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#interrupt)
3. [Os Oh yes 3장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#process-thread)

## 다음주 목표 3가지를 적어주세요

1. Os Oh yes 4장
2. 5장
3. 6장

### CODE REVIEW

**Review by PARKINHYO — APPROVED** [review]
수고하셨습니다!! 즐거운 연휴 되세요~ㅎ

**Review by kerochuu — APPROVED** [review]
허허 수고하셨습니다~

**Review by nook1208 — APPROVED** [review]
LGTM

**Review by 1ilsang — APPROVED** [review]
님 우리 레포에도 정리해주시져

**Pull request merged**
